#!/bin/bash

FAIL=0
RC=$1;   shift;
TEST=$1; shift;
TEMP=`mktemp extap.$$.XXXXXXXXXX`

$@ > $TEMP 2>&1
if [[ $? == $RC ]]; then
	echo "ok - exit code $? == $RC"
else
	echo "not ok - exit code $? != $RC"
	FAIL=1
fi
GOT_SHA1=`cat $TEMP | sha1sum`
EXP_SHA1=`cat $TEST | sha1sum`

if [[ "$GOT_SHA1" == "$EXP_SHA1" ]]; then
	echo "ok - output as expected"
else
	echo "not ok - output not as expected"
	echo "#      got sha1: $GOT_SHA1"
	echo "# expected sha1: $EXP_SHA1"
	diff -u $TEST $TEMP | sed -e 's/^/# /'
	echo "#   ran command: \`$@'"
fi

echo "1..2"
rm -f $TEMP
exit $FAIL;
